# Generated by Django 5.2.9 on 2026-01-30 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alerttype_alert_alert_type_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_type',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.alerttype'),
            preserve_default=False,
        ),
    ]
