# Generated by Django 5.2.9 on 2026-01-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_remove_alert_alert_type_alter_alert_alert_type_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='alert_type_link',
            new_name='alert_type',
        ),
    ]
