# Generated by Django 5.2.9 on 2026-01-30 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_rename_alert_type_link_alert_alert_type'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlertType',
            new_name='AlertDefinition',
        ),
        migrations.RenameModel(
            old_name='Alert',
            new_name='TripAlert',
        ),
    ]
