# Generated by Django 5.2.9 on 2026-01-30 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_rename_alerttype_alertdefinition_tripalert_and_more'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripalert',
            options={'verbose_name': 'Trip Alert', 'verbose_name_plural': 'Trip Alerts'},
        ),
        migrations.AlterField(
            model_name='tripalert',
            name='alert_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_alerts', to='alerts.alertdefinition'),
        ),
        migrations.AlterField(
            model_name='tripalert',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_alerts', to='trips.trip'),
        ),
        migrations.AlterField(
            model_name='tripalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
