# Generated by Django 5.2.9 on 2026-01-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alter_tripalert_options_alter_tripalert_alert_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlertDefinition',
            new_name='Alert',
        ),
    ]
