# Generated by Django 5.2.9 on 2026-02-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_rename_alertdefinition_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripalert',
            name='vehicle_speed',
            field=models.FloatField(blank=True, help_text='Speed in km/h', null=True),
        ),
        migrations.AlterField(
            model_name='tripalert',
            name='severity',
            field=models.CharField(choices=[('MINOR_RISK', 'Minor Risk'), ('MODERATE_RISK', 'Moderate Risk'), ('CRITICAL_RISK', 'Critical Risk')], default='MODERATE_RISK', max_length=20),
        ),
    ]
