# Generated by Django 5.2.9 on 2026-02-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicles',
        ),
    ]
